### ISSUE TITLE
bug en script de BIP

### ISSUE THREAD

**Issue by juanbrujo** [devschile/huemul#153]
```
huemul> Huemul Bip 08360996
huemul> La consulta va en la micro... espere harto... :clock5:
[Fri Jan 20 2017 10:41:19 GMT-0300 (CLST)] ERROR SyntaxError: Unexpected end of input
  at Object.parse (native)
  at /Library/WebServer/Documents/huemul/scripts/bip.coffee:37:11, <js>:21:25
  at IncomingMessage.<anonymous> (/Library/WebServer/Documents/huemul/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
  at emitNone (events.js:72:20)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:913:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)
```

**Comment by juanbrujo** [comment]
cagó la API. alguien conoce otra?

`http://www.psep.cl/api/Bip.php?&numberBip=08360996`

**Comment by rampmaster** [comment]
Notifique al Dev de la api para ver que se puede hacer

**Comment by juanbrujo** [comment]
ya cambié la API y está en el PR https://github.com/devschile/huemul/pull/152 esperando que se mergee :gmq:--
